config/routes.rb
GreenMarketMe::Application.routes.draw do
  resources :markets

    root :to => 'markets#index'

end

app/models/market.rb
class Market < ActiveRecord::Base
  attr_accessible :address, :borough, :days_open, :name, :gmaps, :latitude, :longitude, :hours, :distribute_health_bucks, :accepts_health_bucks, :accepts_EBT, :stellar
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
  
  acts_as_gmappable




   def gmaps4rails_address
   "#{self.address}, New York, New York"
   end

  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE :search OR borough LIKE :search', {:search => "%#{search}%"}])
    else
      scoped
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  require 'will_paginate/array'
  
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  # GET /markets
  # GET /markets.json
  helper_method :sort_column, :sort_direction

  def index

    @markets = Market.search(params[:search]).uniq{|market| market.name}.order(sort_column + " " + sort_direction)
    @boroughs = ["Manhattan", "Queens", "Bronx", "Brooklyn", "Staten Island"]
    @days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
    @markers = @markets.to_gmaps4rails do |market|
       "\"title\": \"#{market.name}\"" 
     end 

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @markets }
    end
  end

  # GET /markets/1
  # GET /markets/1.json
  def show
    @market = Market.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @market }
    end
  end

  # GET /markets/new
  # GET /markets/new.json
  def new
    @market = Market.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @market }
    end
  end

  # GET /markets/1/edit
  def edit
    @market = Market.find(params[:id])
  end

  # POST /markets
  # POST /markets.json
  def create
    @market = Market.new(params[:market])

    respond_to do |format|
      if @market.save
        format.html { redirect_to @market, notice: 'Market was successfully created.' }
        format.json { render json: @market, status: :created, location: @market }
      else
        format.html { render action: "new" }
        format.json { render json: @market.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /markets/1
  # PUT /markets/1.json
  def update
    @market = Market.find(params[:id])

    respond_to do |format|
      if @market.update_attributes(params[:market])
        format.html { redirect_to @market, notice: 'Market was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @market.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markets/1
  # DELETE /markets/1.json
  def destroy
    @market = Market.find(params[:id])
    @market.destroy

    respond_to do |format|
      format.html { redirect_to markets_url }
      format.json { head :no_content }
    end
  end
 
  private
  
  def sort_column
    Market.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
  end

end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GreenMarketMe</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

  <% if Rails.env.development? %>
        <div id="dev-tools" style="border:2px solid #eee;margin-top:30px;text-align:center;">
            <strong>DEV</strong> <%= params %>
        </div>
  <% end %>

</body>
</html>

app/views/markets/_form.html.erb
<%= form_for(@market) do |f| %>
  <% if @market.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@market.errors.count, "error") %> prohibited this market from being saved:</h2>

      <ul>
      <% @market.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :borough %><br />
    <%= f.text_field :borough %>
  </div>
  <div class="field">
    <%= f.label :days_open %><br />
    <%= f.text_field :days_open %>
  </div>
    <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>




  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/markets/_map_and_table_index_view.html.erb
<h1>NYC Green Markets</h1>
<%= gmaps4rails(@markers) %>

<%= form_tag markets_path, :method => 'get', :id => "products_search" do %>
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <div id="markets"><%#= render 'markets' %></div>
<% end %>

<table>
  <tr>
    <th><%= sortable "Name"%></th>
    <th>Address</th>
    <th><%= sortable "Borough"%></th>
    <th>Latitude</th>
    <th>Longitude</th>
  </tr>
  <% for market in @markets %>
    <tr>
      <td><%= market.name %></td>
      <td><%= market.address %></td>
      <td><%= market.borough %></td>
      <td><%= market.latitude %></td>
      <td><%= market.longitude %></td>
      <td><%= link_to "Show", market %></td>
      <td><%= link_to "Edit", edit_market_path(market) %></td>
      
    </tr>
  <% end %>
</table>


<%= yield :scripts %>

<%#= will_paginate @markets %>

<%= link_to 'New Market', new_market_path %>

app/views/markets/_market_isotopes.html.erb
<h1>NYC Green Markets</h1>
<div id ="options" class="clearfix">
  <ul id ="filters" class="option-set clearfix" >
        <li> <a href="#" data-filter="*" class="selected">Show All</a></li>
      <% @boroughs.each do |borough| %>
        <li><a href="#" data-filter=".<%= borough.gsub(/\s+/, "") %>"><%=borough %></a></li>
      <% end %>
     
  </ul>
   <ul id ="filters" class="option-set clearfix" >
        <li> <a href="#" data-filter="*" class="selected">Show All</a></li>
      <% @days.each do |day| %>
        <li><a href="#" data-filter=".<%= day %>"><%= day %></a></li>
      <% end %>
     
  </ul>
</div> 

<div id="container">

  <% @markets.each do |market| %>
    <div class="element <%=market.borough.gsub(/\s+/, "") %> <%=market.days_open %> ">
      <%= market.name %>

      <%= market.borough %>

     <%= market.days_open %>

      <%= market.hours %>

      <%= market.address %>

      <%= 'EBT' if market.accepts_EBT %>

      <%= 'Stellar' if market.stellar %>
    </div>

  <% end %>

</div>

app/views/markets/edit.html.erb
<h1>Editing market</h1>

<%= render 'form' %>

<%= link_to 'Show', @market %> |
<%= link_to 'Back', markets_path %>

app/views/markets/index.html.erb
<%= render 'market_isotopes' %> 

app/views/markets/new.html.erb
<h1>New market</h1>

<%= render 'form' %>

<%= link_to 'Back', markets_path %>

app/views/markets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @market.name %>
</p>

<p>
  <b>Address:</b>
  <%= @market.address %>
</p>

<p>
  <b>Borough:</b>
  <%= @market.borough %>
</p>

<p>
  <b>Days open:</b>
  <%= @market.days_open %>
</p>


<%= link_to 'Edit', edit_market_path(@market) %> |
<%= link_to 'Back', markets_path %>